USER_STATUS = {"ACTIVE": 0, "INACTIVE": 1}
STATUS_ACTIVE = 1
CREATION_BY = "system"
UPDATION_BY = "system"

#error handling
ERROR_AMOUNT = "ERROR_AMOUNT"
ERROR_NUMERIC = "ERROR_NUMERIC"
ERROR_DATE = "ERROR_DATE"
