# Generated by Django 3.2.8 on 2022-01-25 08:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('salutation', models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
                ('first_name', models.TextField()),
                ('middle_name', models.TextField(null=True)),
                ('last_name', models.TextField(null=True)),
                ('gender', models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
                ('date_of_birth', models.DateTimeField(null=True)),
                ('relation_with_applicant', models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
                ('marital_status', models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
                ('father_first_name', models.TextField(null=True)),
                ('father_middle_name', models.TextField(null=True)),
                ('father_last_name', models.TextField(null=True)),
                ('mother_first_name', models.TextField(null=True)),
                ('mother_middle_name', models.TextField(null=True)),
                ('mother_last_name', models.TextField(null=True)),
                ('spouse_first_name', models.TextField(null=True)),
                ('spouse_middle_name', models.TextField(null=True)),
                ('spouse_last_name', models.TextField(null=True)),
                ('no_of_family_members', models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)])),
                ('household_income_monthly', models.IntegerField(max_length=20, null=True)),
                ('status', models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
                ('creation_date', models.DateTimeField()),
                ('creation_by', models.TextField()),
                ('updation_date', models.DateTimeField(null=True)),
                ('updation_by', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customerauditlog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('salutation', models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
                ('first_name', models.TextField()),
                ('middle_name', models.TextField(null=True)),
                ('last_name', models.TextField(null=True)),
                ('gender', models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
                ('date_of_birth', models.DateTimeField(null=True)),
                ('relation_with_applicant', models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
                ('marital_status', models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
                ('father_first_name', models.TextField(null=True)),
                ('father_middle_name', models.TextField(null=True)),
                ('father_last_name', models.TextField(null=True)),
                ('mother_first_name', models.TextField(null=True)),
                ('mother_middle_name', models.TextField(null=True)),
                ('mother_last_name', models.TextField(null=True)),
                ('spouse_first_name', models.TextField(null=True)),
                ('spouse_middle_name', models.TextField(null=True)),
                ('spouse_last_name', models.TextField(null=True)),
                ('no_of_family_members', models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)])),
                ('household_income_monthly', models.IntegerField(max_length=20, null=True)),
                ('status', models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
                ('creation_date', models.DateTimeField()),
                ('creation_by', models.TextField()),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='los.customer')),
            ],
        ),
    ]
