# Generated by Django 3.2.8 on 2022-02-10 15:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('los', '0002_contact'),
    ]

    operations = [

        migrations.AlterField(
            model_name='contact',
            name='country_code',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AlterModelTable(
            name='contact',
            table='customer_contact',
        ),
        migrations.AlterModelTable(
            name='customerauditlog',
            table='customer_log',
        ),
        migrations.CreateModel(
            name='ContactLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
                ('value', models.TextField()),
                ('value_extra_1', models.TextField(null=True)),
                ('country_code', models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)])),
                ('status', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
                ('creation_date', models.DateTimeField()),
                ('creation_by', models.TextField()),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='los.customer')),
            ],
            options={
                'db_table': 'customer_contact_log',
            },
        ),
    ]
