# Generated by Django 3.2.8 on 2022-02-12 14:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('los', '0003_auto_20220210_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='household_income_monthly',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999999999)]),
        ),
        migrations.AlterField(
            model_name='customerauditlog',
            name='household_income_monthly',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
