# Generated by Django 3.2.8 on 2022-02-12 12:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('los', '0003_auto_20220210_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('salutation', models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
                ('first_name', models.TextField()),
                ('middle_name', models.TextField(null=True)),
                ('last_name', models.TextField(null=True)),
                ('gender', models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
                ('date_of_birth', models.DateTimeField(null=True)),
                ('relation_with_applicant', models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
                ('marital_status', models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
                ('father_first_name', models.TextField(null=True)),
                ('father_middle_name', models.TextField(null=True)),
                ('father_last_name', models.TextField(null=True)),
                ('mother_first_name', models.TextField(null=True)),
                ('mother_middle_name', models.TextField(null=True)),
                ('mother_last_name', models.TextField(null=True)),
                ('spouse_first_name', models.TextField(null=True)),
                ('spouse_middle_name', models.TextField(null=True)),
                ('spouse_last_name', models.TextField(null=True)),
                ('no_of_family_members', models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)])),
                ('household_income_monthly', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999999999)])),
                ('status', models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
                ('creation_date', models.DateTimeField()),
                ('creation_by', models.TextField()),
            ],
            options={
                'db_table': 'los_customer_log',
            },
        ),
        migrations.RenameModel(
            old_name='Contact',
            new_name='CustomerContact',
        ),
        migrations.RenameModel(
            old_name='ContactLog',
            new_name='CustomerContactLog',
        ),
        migrations.AlterField(
            model_name='customer',
            name='household_income_monthly',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999999999)]),
        ),
        migrations.AlterModelTable(
            name='customercontact',
            table='los_customer_contact',
        ),
        migrations.AlterModelTable(
            name='customercontactlog',
            table='los_customer_contact_log',
        ),
        migrations.DeleteModel(
            name='Customerauditlog',
        ),
        migrations.AddField(
            model_name='customerlog',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='los.customer'),
        ),
    ]
