# Generated by Django 3.2.8 on 2022-02-14 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('los', '0004_auto_20220212_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercontactlog',
            name='contact',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='los.customercontact'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customercontact',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='los.customer'),
        ),
        migrations.AlterField(
            model_name='customercontactlog',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='los.customer'),
        ),
    ]
