# Generated by Django 3.2.8 on 2022-02-15 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('los', '0006_rename_contact_customercontactlog_customercontact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customercontactlog',
            old_name='customercontact',
            new_name='customer_contact',
        ),
    ]
